### ISSUE TITLE
Debug Chezy shooter jam

### ISSUE THREAD

**Issue by Owen756** [team581/2024-offseason-comp#104]
Check Logs, etc.

**Comment by jonahsnider** [comment]
To add more detail:
- This happened in our last Chezy Champs 2024 match
- Can review match video to try and figure out cause
- The shooter motors felt hot after the match, so likely they were stalling (note stuck on something?)
- Need to check regular logs and probably hoot file to check motor logs
- Goal is to consistently reproduce this at home, and figure out how to avoid it (or at least how to unjam better)

**Comment by simonstoryparker** [comment]
[https://www.youtube.com/live/OSzAP4t2i-Y?si=3jfVvdhgp198qgJT&t=19626
](url)
5:27:06 - 5:27:34

**Comment by rhetorr** [comment]
note was already jammed during the handoff
