### ISSUE TITLE
Tune note health

### ISSUE THREAD

**Issue by simonstoryparker** [team581/2024-offseason-comp#113]
Right now, our note health is 10 for all notes (per NoteMapElement.java).

From testing, it seems that bounding box is not sensitive enough to get rid of the note when driving up to it. 

First try to decrease it from 10 to 5. Goal is to be able to drive up to missing midline note, and skip it in time to not hit a robot that is potentially getting that note. 

We're aiming for zero bumper to bumper time when getting midline notes.

That being said, if a note is ever skipped even though it's still there, the default health should be increased. Health should be tuned before bounding box corner coordinates or safeToTrack speeds, which are already pretty dialed in.

**Comment by jonahsnider** [comment]
We decided to crank up the health to like 20, since we aren't super confident in bounding box and want to only remove notes when we are very confident they're missing.
