### ISSUE TITLE
Use a bounding box for scoring in note map

### ISSUE THREAD

**Issue by simonstoryparker** [team581/2024-offseason-comp#54]
Currently, we have fixed scoring positions. However, it takes time to pathfinding to a scoring position, which is unnecessary when we're already in a place we can shoot from. We should make a simple bounding box around the area we can shoot from, and we can add a .unless() to the scoreCommand() that checks if our robot is in the scoring box.

**Comment by jonahsnider** [comment]
Probably something like this is what we want it to be. Goals:
- Can shoot if right by speaker
- Can't shoot if too close to wing line/too far from speaker
- Can't shoot if all the way to the side of the speaker, or other crazy angle needed to score

![Drawn zone of valid shots in red wing](https://github.com/user-attachments/assets/de2f9c2f-c255-4e0d-be67-071b48cd96e4)

**Comment by jonahsnider** [comment]
I will also add that this only really matters for scoring notes that aren't from the midline. So honestly, this probably isn't going to be that useful unless we're running cleanup mode. Keep this in mind when evaluating priorities on what to add to note map.
